sudo: false
language: node_js

cache:
  directories:
    - ~/.yarn-cache
    - node_modules
    - www/node_modules

matrix:
  include:
    - os: linux
      node_js: "8"
      env: NO_WATCH_TESTS=1
    - os: osx
      node_js: "8"
      env: NO_WATCH_TESTS=1
  allow_failures:
    - os: osx
fast_finish: true

after_success:
  - node_modules/.bin/codecov
