language: node_js

cache:
  directories:
    - ~/.yarn-cache
    - node_modules
    - www/node_modules

jobs:
  include:
    - os: linux
      node_js: "10"
      env: NO_WATCH_TESTS=1
    - os: osx
      node_js: "10"
      env: NO_WATCH_TESTS=1
  allow_failures:
    - os: osx

after_success:
  - yarn codecov
